flowchart TD

A[Inicio tienda] --> B[Seleccionar tipo documento y numero]

B --> C{Cliente existe}

C -- Si --> Z[Ir Bloque 2 Validacion cupo]

C -- No --> F{Tipo creacion}

F -- OCR --> G[Capturar documento]
G --> G1[Extraer datos]
G1 --> G2[Editar datos]
G2 --> I{Datos completos}

F -- Manual --> H[Ingresar datos manuales]
H --> I

I -- No --> J[Completar informacion]
J --> I

I -- Si --> K{Correo valido}

K -- No --> L[Corregir correo]
L --> K

K -- Si --> M{Correo o celular duplicado}

M -- Si --> M1[Aplicar regla]
M1 --> N[Cliente listo]

M -- No --> N

N --> O{Autogestion}

O -- Si --> P[Generar link]
P --> Q[Asociar origen]
Q --> R[Enviar link]
R --> S[Continua flujo web]

O -- No --> T[Ir Bloque 3 Inicio estudio]